### ISSUE TITLE
Cannot Use gdscript-debug-add-breakpoint

### ISSUE THREAD

**Issue by matthew-a-schultz** [godotengine/emacs-gdscript-mode#110]
If I try C-c C-d b

I get "C-c C-d b is undefined"

If I try and execute gdscript-debug-add-breakpoint manually I get a "no-match" error.

I can use the gdscript-debug-toggle-breakpoint command to set a breakpoint.

Emacs on Mac installed package from package-install

**Comment by matthew-a-schultz** [comment]
I've looked into this and it appears the docs are outdated. It looks like all there is now is gdscript-debug-toggle-breakpoint. This would be fine however the breakpoint is not showing in the fringe using either Flymake or Flycheck.

**Comment by NathanLovato** [comment]
I'll update the docs right away. As far as displaying breakpoints in the fringe, I can confirm. The debugger support is a bit of a pain as there's no standardized way to do that in Emacs and in Godot. I think it's best to wait for DAP support in Godot because right now it's a bit clunky. Note that the display thing should be a separate bug report.
